# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42b51748a9b8acdb65a740a5cf09a39593ce2483c1e3be69ee7145ee8a47284ce1399cca4f3fde2a4a6885ba435214ebe47e849948538ead60f63ed0789f3aa9

test:
  secret_key_base: 63e27c6531449db85f14b034b5bb6c8f01bca8e0e32592a6d2798c0a2920252a66c7d1f943cc740f01f0bcb5b3e9ad737270165f7acf5209c20926e3c3a89f30

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
